project/Usuario/urls.py
from django.urls import path
from .views import home, lista_usuarios, create_usuario, acerca_de, usuario_delete, usuario_update, register, user_login, user_logout



app_name = "Usuario"

urlpatterns = [
    path("", home, name="home"),
    path("lista", lista_usuarios, name="lista"),
    path("create", create_usuario, name="agregar_usuarios"),
    path("acerca_de", acerca_de, name="acerca_de"),
    path("modificar/<int:pk>", usuario_update, name="usuario_update"),
    path("borrar/<int:pk>", usuario_delete, name="usuario_delete"),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

project/catalogo/urls.py
from django.urls import path
from .views import home, lista_catalogo, lista_create, catalogo_delete, catalogo_update


app_name = "catalogo"

urlpatterns = [
    path("", home, name="home"),
    path("lista", lista_catalogo, name="lista_catalogo"),
    path("lista/create", lista_create, name="lista_create"),
    path("update/<int:pk>", catalogo_update, name="catalogo_update"),
    path("catalogo/catalogo_delete/<int:pk>/", catalogo_delete, name="catalogo_delete")
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
#from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("Usuario/", include("Usuario.urls")),
    path("catalogo/", include("catalogo.urls")),
]

project/core/urls.py
from django.urls import path
from core.views import home

app_name = "core"
urlpatterns = [
    path("", home, name="home")
]

project/Usuario/models.py
from django.db import models

class Provincia(models.Model):
    nombre = models.CharField(max_length=35)

    def __str__(self) -> str:
        return self.nombre



class Usuario(models.Model):
    dni = models.CharField(max_length=8)
    nombre = models.CharField(max_length=30)
    telefono =  models.CharField(max_length=12)
    provincia = models.ForeignKey(Provincia, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        return self.dni

project/catalogo/models.py
from django.db import models

class NuevoProducto(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    marca = models.CharField(max_length=50, unique=True)
    año =  models.CharField(max_length=50, unique=True)


    def __str__(self) -> str:
        return  f"{self.nombre} {self.marca} {self.año}"

project/core/models.py
from django.db import models

# Create your models here.

project/Usuario/forms.py
from django import forms
from . import models

class NuevoUsuarioForm(forms.ModelForm):
    class Meta:
        model = models.Usuario
        fields = ["nombre", "dni", "telefono", "provincia"]

project/catalogo/forms.py
from django import forms
from . import models

class NuevoProductoForm(forms.ModelForm):
    class Meta:
        model = models.NuevoProducto
        fields = ["nombre", "marca", "año"]

project/Usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect, get_object_or_404
from .models import Usuario
from Usuario.forms import NuevoUsuarioForm

def home(request):
    return render(request, "Usuario/index.html")

def lista_usuarios(request):
    lista = Usuario.objects.all()
    contexto = {"Usuarios" : lista}
    return render(request, "Usuario/lista_usuarios.html", contexto)

def create_usuario(request):
    if request.method == "POST":
        formulario = NuevoUsuarioForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return render(request, "Usuario/lista_usuarios.html")
    else:
        formulario = NuevoUsuarioForm()
    return render(request, "Usuario/agregar_usuarios.html", {"formulario": formulario})

def acerca_de(request):
    return render(request, "Usuario/acerca_de.html")

def usuario_update(request,pk):
    consulta = Usuario.objects.get(id=pk)
    if request.method == "POST":
        form = NuevoUsuarioForm(request.POST, instance=consulta)
        if form.is_valid():
            form.save()
            return redirect("http://127.0.0.1:8000/Usuario/lista")
    else:
        form =  NuevoUsuarioForm(instance=consulta)
    return render(request, "Usuario/usuario_update.html", {"form": form})

def usuario_delete(request, pk):
    consulta = get_object_or_404(Usuario, id=pk)
    if request.method == "POST":
        consulta.delete()
        return redirect("http://127.0.0.1:8000/Usuario/lista")
    return render(request, "Usuario/usuario_delete.html", {"object": consulta})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('http://127.0.0.1:8000/')
    else:
        form = UserCreationForm()
    return render(request, 'Usuario/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('http://127.0.0.1:8000/') 
    else:
        form = AuthenticationForm()
    return render(request, 'Usuario/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('http://127.0.0.1:8000/')

project/catalogo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import NuevoProducto
from catalogo.forms import NuevoProductoForm

def home(request):
    return render(request, "catalogo/index.html")

def lista_catalogo(request):
    lista = NuevoProducto.objects.all()
    contexto = {"catalogo" : lista}
    return render(request, "catalogo/lista_catalogo.html", contexto)

def lista_create(request):
    if request.method == "POST":
        form = NuevoProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "catalogo/lista_catalogo.html")
    else:
        form = NuevoProductoForm()
    return render(request, "catalogo/lista_create.html", {"form": form})

"""def buscar(request):
    busqueda = request.GET.get("busqueda", None)
    if busqueda:
        print(busqueda)
        consulta = NuevoProducto.objects.filter(nombre__icontains=busqueda)
    else:
        consulta = NuevoProducto.objects.all()
    contexto = {"NuevoProducto" : consulta}
    return render(request, "catalogo/lista_catalogo", contexto)"""

def catalogo_update(request,pk):
    consulta = NuevoProducto.objects.get(id=pk)
    if request.method == "POST":
        form = NuevoProductoForm(request.POST, instance=consulta)
        if form.is_valid():
            form.save()
            return redirect("catalogo:lista_create")
    else:
        form = NuevoProductoForm(instance=consulta)
    return render(request, "catalogo/lista_create.html", {"form": form})

def catalogo_delete(request, pk):
    consulta = get_object_or_404(NuevoProducto, id=pk)
    if request.method == "POST":
        consulta.delete()
        return redirect("catalogo:lista_catalogo")
    return render(request, "catalogo/catalogo_delete.html", {"object": consulta})

project/config/views.py
from django.http import HttpResponse
from django.shortcuts import render

project/core/views.py
from django.shortcuts import render

def home(request):
    return render(request, "core/index.html")

project/Usuario/templates/Usuario/acerca_de.html
{% extends 'core/base.html' %}
{% block content %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Información del Proyecto</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
            color: #333;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        h1 {
            font-size: 2em;
            color: #007bff;
            margin-bottom: 20px;
        }

        p {
            font-size: 1.1em;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Información del Proyecto</h1>
        <p>Este modelo de página o mejor dicho proyecto se realizó en el año 2024 en el curso de "Programación: Python"
           de CoderHouse. Ofrece una simulación de una página de compra virtual. Fue realizada por el alumno Tomás Olivieri,
           con el tutor Juan Manuel Romano y el profesor Esteban Acevedo. Espero que sea de su agrado esta muestra,
           cualquier ayuda, consejo o solución seria perfecto de escuchar! Una vez dicho eso, son libres de indagar por toda esta pagina,
           y su codigo programado con HTML y Python
        </p>
    </div>
</body>
</html>
{% endblock content %}

project/Usuario/templates/Usuario/agregar_usuarios.html
{% extends 'core/base.html' %}
{% block title %}
    Usuarios 
{% endblock title %}
        <title>app USUARIOS </title>
        {% block content %}
            
        <h1>LISTA DE Usuarios REGISTRADOS</h1>
        {% for Usuario in Usuarios  %}
        <h1>-----------</h1>
        <h4>{{Usuario}}</h4>

        {% endfor %}

        <form action="" method="post">
            {% csrf_token %}
            {{formulario}}
            <button type="submit">Guardar</button>
        </form>
{% endblock content %}

project/Usuario/templates/Usuario/index.html
{% extends 'core/base.html' %}
{% block title %}
    Proyecto CoderHouse
{% endblock title %}

{% block content %}
<h2>Usuario</h2>
<button><a href="http://127.0.0.1:8000/Usuario/lista">Lista de usuarios</a></button>
<button><a href="http://127.0.0.1:8000/Usuario/create">Crear usuario</a></button>
</body>
</html>
{% endblock content %}

project/Usuario/templates/Usuario/lista_usuarios.html
{% extends 'core/base.html' %}
{% block title %}
    Usuario | Lista de usuarios
{% endblock title %}
            <title>app Usuario | Lista de usuarios</title>
        {% block content %}
            
        <h1>LISTA DE USUARIOS REGISTRADOS</h1>
        {% for usuario in Usuarios  %}  
        <h4>{{usuario.dni}}</h4>
        <h4>{{usuario.nombre}}</h4>
        <button><a href="{% url 'Usuario:usuario_update' pk=usuario.id%}">Modificar usuario</a></button>
        <button><a href="{% url 'Usuario:usuario_delete' pk=usuario.id%}">Borrar usuario</a></button>
        <h1>-----------</h1>

        {% endfor %}

        </body>
        </html>
{% endblock content %}

project/Usuario/templates/Usuario/login.html
{% extends 'core/base.html' %}
{% block title %}
    Iniciar sesion
{% endblock title %}

    {% block content %}

    <!DOCTYPE html>
    <html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Iniciar sesión</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f0f0f0;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
            }

            .login-container {
                background-color: #fff;
                padding: 20px;
                border-radius: 5px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }

            .login-container h1 {
                text-align: center;
                margin-bottom: 20px;
            }

            .login-form {
                max-width: 300px;
                margin: 0 auto;
            }

            .login-form input[type="text"],
            .login-form input[type="password"] {
                width: 100%;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #ccc;
                border-radius: 5px;
            }

            .login-form button[type="submit"] {
                width: 100%;
                padding: 10px;
                background-color: #007bff;
                color: #fff;
                border: none;
                border-radius: 5px;
                cursor: pointer;
                transition: background-color 0.3s;
            }

            .login-form button[type="submit"]:hover {
                background-color: #0056b3;
            }
        </style>
    </head>
    <body>
        <div class="login-container">
            <h1>Iniciar sesión</h1>
            <form class="login-form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Iniciar sesión</button>
            </form>
        </div>
    </body>
    </html>
    {% endblock content %}

project/Usuario/templates/Usuario/register.html
{% extends 'core/base.html' %}
{% block title %}
    Registrarse
{% endblock title %}

{% block content %}
    <!DOCTYPE html>
    <html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registro de Usuario</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f0f0f0;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
            }

            .register-container {
                background-color: #fff;
                padding: 20px;
                border-radius: 5px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }

            .register-container h1 {
                text-align: center;
                margin-bottom: 20px;
            }

            .register-form {
                max-width: 300px;
                margin: 0 auto;
            }

            .register-form input[type="text"],
            .register-form input[type="password"] {
                width: 100%;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #ccc;
                border-radius: 5px;
            }

            .register-form button[type="submit"] {
                width: 100%;
                padding: 10px;
                background-color: #007bff;
                color: #fff;
                border: none;
                border-radius: 5px;
                cursor: pointer;
                transition: background-color 0.3s;
            }

            .register-form button[type="submit"]:hover {
                background-color: #0056b3;
            }
        </style>
    </head>
    <body>
        <div class="register-container">
            <h1>Registro de Usuario</h1>
            <form class="register-form" method="POST" action="{% url 'Usuario:register' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Registrarse</button>
            </form>
        </div>
    </body>
    </html>
{% endblock content %}

project/Usuario/templates/Usuario/usuario_delete.html
{% extends 'core/base.html' %}
{% block title %}
    Usuario
{% endblock title %}
<title>app Usuario | Borrar usuario</title>
{% block content %}
            
<h1>¿Estás seguro de que deseas eliminar {{ object.nombre }}?</h1>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Confirmar eliminación</button>
    <a href="http://127.0.0.1:8000/Usuario/lista">Cancelar</a>
</form>

{% endblock content %}

project/Usuario/templates/Usuario/usuario_update.html
{% extends 'core/base.html' %}
{% block title %}
    Modificar usuarios
{% endblock title %}
<title>app USUARIO</title>
{% block content %}
            
<div class="container mt-5">
    {% if form.instance.pk %}
        <h1 class="text-center">Modificar usuario</h1>
    {% else %}
        <h1 class="text-center">Editar usuario</h1>
    {% endif %}
    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <table class="table table-bordered">
                            {{ form.as_table }}
                        </table>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                            <a href="" type="button" class="btn btn-dark ">Cancelar</button></a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

project/catalogo/templates/catalogo/catalogo_delete.html
{% extends 'core/base.html' %}
{% block title %}
    Producto | Producto categoria
{% endblock title %}
<title>app CATALOGO | Borrar Producto</title>
{% block content %}
            
<h1>¿Estás seguro de que deseas eliminar {{ object.nombre }}?</h1>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Confirmar eliminación</button>
    <a href="{% url 'catalogo:lista_catalogo' %}">Cancelar</a>
</form>

{% endblock content %}

project/catalogo/templates/catalogo/catalogo_form.html
{% extends 'core/base.html' %}
{% block title %}
    Producto | Producto categoria
{% endblock title %}
<title>app CATALOGO | Borrar Producto</title>
{% block content %}
            
<div class="container mt-5">
    {% if form.instance.pk %}
        <h1 class="text-center">Modificar Prestador</h1>
    {% else %}
        <h1 class="text-center">Editar Prestador</h1>
    {% endif %}
    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <table class="table table-bordered">
                            {{ form.as_table }}
                        </table>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                            <a href="{% url 'medicos:medicos_list' %}" type="button" class="btn btn-dark ">Cancelar</button></a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

project/catalogo/templates/catalogo/catalogo_update.html
{% extends 'core/base.html' %}
{% block title %}
    Producto | Producto categoria
{% endblock title %}
<title>app CATALOGO | Borrar Producto</title>
{% block content %}
            
<div class="container mt-5">
    {% if form.instance.pk %}
        <h1 class="text-center">Modificar Prestador</h1>
    {% else %}
        <h1 class="text-center">Editar Prestador</h1>
    {% endif %}
    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <table class="table table-bordered">
                            {{ form.as_table }}
                        </table>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                            <a href="{% url 'medicos:medicos_list' %}" type="button" class="btn btn-dark ">Cancelar</button></a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

project/catalogo/templates/catalogo/index.html
{% extends 'core/base.html' %}
{% block title %}
    Proyecto CoderHouse | Catalogo
{% endblock title %}

{% block content %}
<h2>catalogo</h2>
<button><a href="{% url 'catalogo:lista_catalogo' %}">Lista de los nuevos ingresos al catalogo</a></button>
<button><a href="{% url 'catalogo:lista_create' %}">Crear lista de catalogo</a></button>
</html>
{% endblock content %}

project/catalogo/templates/catalogo/lista_catalogo.html
{% extends 'core/base.html' %}
{% block title %}
Catalogo | Lista de productos
{% endblock title %}
<title>app CATALOGO | Lista de productos</title>
{% block content %}


<form action="{% url 'catalogo:lista_catalogo' %}" method="get">
    <input type="text" name="busqueda" placeholder="Buscar..."><button>Buscar</button>
</form>
<h1>LISTA DE PRODUCTOS</h1>
{% for catalogo in catalogo %}
<h1>-----------</h1>
<h4>{{catalogo}}</h4>
<button><a href="{% url 'catalogo:catalogo_delete' pk=catalogo.id %}">Borrar Producto</a></button>
<button><a href="{% url 'catalogo:catalogo_update' pk=catalogo.id%}">Modificar Catalogo</a></button>
{% endfor %}


{% endblock content %}

project/catalogo/templates/catalogo/lista_create.html
{% extends 'core/base.html' %}
{% block title %}
    Producto | Producto categoria
{% endblock title %}
        <title>app CATALOGO | Lista de productos</title>
{% block content %}
            
{% if form.instance.pk %}
<h1 class="text-center">Crear nuevo Catalogo</h1>
{% else %}
<h1 class="text-center">Crear Catalogo</h1>
{% endif %}

        {% for catalogo in catalogo  %}
        <h4>{{catalogo}}</h4>
        {% endfor %}

        {% for catalogo in catalogo  %}
        <h1>-----------</h1>
        <h4>{{catalogo}}</h4>

        {% endfor %}

        <form method="POST">
            {% csrf_token %}
            <table class="table table-bordered">
                {{ form.as_table }}
            </table>
            <div class="text-center">
                <button type="submit">Guardar Cambios</button>
                <a href="{% url 'catalogo:lista_catalogo' %}" type="button" >Cancelar</button></a>
            </div>
        </form>

{% endblock content %}

project/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Tomas Olivieri" />
        <title>{% block title %}
            
        {% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="http://127.0.0.1:8000/">Proyecto CoderHouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/">inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/Usuario/acerca_de">Acerca de</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Opciones</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'Usuario:home' %}">Usuario</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'catalogo:home' %}">Lista de Catalogos </a></li>
                            </ul>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/Usuario/login">Iniciar sesion</a></li>
                        <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/Usuario/register">Registrarse</a></li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <h1>{% block body_title %}
            {% endblock body_title %}</h1>

        {% block content %}
            
        {% endblock content %}
        <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; CoderHouse</p></div>
    </footer>
    </body>
    </html>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/templates/template1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>